import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    ChangeLanguage: "Change Language",
    Logout: "Logout",
    PhysicalData: "Physical Data",
    UsefulTips: "Useful Tips",
    PaymentHistory: "Payment History",
    Help: "Help",
    ContactInfo: "Contact Info",
    PushNotifications: "Push Notifications",
    UpdateProfile: "Update Profile",
    Version: "Version",
    Profile: "Profile",
    Add: "Add",
    // Onboarding
    ShipYourParcel: "Ship Your Parcel",
    ShipAnywhere: "Ship Anywhere",
    TrackYourParcel: "Track Your Parcel",
    OnboardingDesc1: "Experience smooth and completely stress-free shipping of your parcel.",
    OnboardingDesc2: "Send your parcel across borders with our reliable and secure shipping service.",
    OnboardingDesc3: "Stay updated and know the real-time location of your shipment anytime.",
    Skip: "Skip",
    Continue: "Continue",
    // Choose Role
    ChooseRole: "Choose your user Role",
    User: "User",
    Delivery: "Delivery",
    PleaseSelectRole: "Please select your role before proceeding.",
    // Profile
    EditProfile: "Edit Profile",
    MyOrders: "My Orders",
    PrivacyPolicy: "Privacy Policy",
    TermsConditions: "Terms and Conditions",
    // Login
    PhoneQuestion: "What's your phone number?",
    PhoneSubtitle: "We'll send you a code to verify it",
    PhoneNumber: "Phone Number",
    SelectCountry: "Select Country",
    SearchCountry: "Search country",
    Cancel: "Cancel",
    PleaseEnterPhone: "Please enter your phone number.",
    PleaseEnterValidPhone: "Please enter a valid phone number (6-15 digits).",
    ContinueWithNumber: "Continue with Number",
    ContinueWithGoogle: "Continue with Google",
    FullName: "Full Name",
    Email: "Email",
    Address: "Address",
    Update: "Update",
    // Status Labels
    StatusPending: "Pending",
    StatusAssigned: "Assigned",
    StatusGoingToPickup: "Going to Pickup",
    StatusPickedUp: "Picked Up",
    StatusOnTheWay: "On the Way",
    StatusArriving: "Arriving",
    StatusDelivered: "Delivered",
    StatusCompleted: "Completed",
    StatusCancelled: "Cancelled",
    // Orders Screen
    Orders: "Orders",
    Pending: "Pending",
    Complete: "Complete",
    Canceled: "Canceled",
    NoOrdersFound: "No orders found",
    TrackingID: "Tracking ID",
    StepXofY: "Step {0} of {1} complete",
    ViewDetails: "View Details",
    WriteAReview: "Write a Review",
    // General
    Search: "Search",
    Notifications: "Notifications",
    Home: "Home",
    Inbox: "Inbox",
    Tracking: "Tracking",
    From: "From",
    To: "To",
    DeliveryStatus: "Delivery Status",
    CreateParcel: "Create Parcel",
    ShippingHistory: "Shipping History",
    SelectDeliveryAddress: "Select your delivery address",
    OfferAccepted: "Offer Accepted",
    DriverAcceptedOffer: "Driver has accepted your counter offer.",
    Order: "Order",
    Carrier: "Carrier",
    OfferPrice: "Offer Price",
    MessageLabel: "Message",
    PhoneLabel: "Phone",
    Accept: "ACCEPT",
    CounterOfferLabel: "COUNTER OFFER",
    Chat: "CHAT",
    Back: "Back",
    OffersForYourAd: "OFFERS FOR YOUR AD",
    NoOffersAvailable: "No offers available for your ad yet.",
    FindingDriver: "Finding Driver",
    DriversLabel: "DRIVERS",
    RadiusLabel: "RADIUS",
    ScanningArea: "SCANNING AREA",
    CancelSearch: "CANCEL SEARCH",
    RetryLabel: "RETRY",
    SearchingDrivers: "Searching for available drivers...",
    ConnectingNetwork: "Connecting to delivery network",
    DriverConfirmed: "Driver confirmed • Preparing pickup",
    DriverEnRoute: "Driver en route • ETA calculating",
    ParcelCollected: "Parcel collected • In transit",
    ParcelDelivered: "Parcel delivered successfully",
    SearchInboxPlaceholder: "Search by name, tracking ID…",
    NoChatsYet: "No chats yet",
    NoConversationsSubtitle: "Your conversations will appear here",
    SessionExpired: "Session expired. Please log in again.",
    FailedLoadChats: "Failed to load chats. Pull down to retry.",
    NoMessagesYet: "No messages yet",
    Unknown: "Unknown",
    Today: "Today",
    Yesterday: "Yesterday",
    DeliveryAgent: "Delivery Agent",
    TypeAMessage: "Type a message…",
    LoadingMessages: "Loading messages…",
    NoMessagesYetSayHi: "No messages yet. Say hi!",
    OrderOpen: "Order Open",
    ErrorLabel: "Error",
    PhoneNotAvailable: "Phone number not available",
    PhoneCallNotSupported: "Phone call not supported",
    SomethingWentWrong: "Something went wrong",
    FailedAcceptOffer: "Failed to accept offer",
    Done: "Done",
    SelectLanguage: "Select Language",
    FailedSendCounterOffer: "Failed to send counter offer",
    CounterOfferSent: "Counter offer sent successfully!",
    OfferAcceptedSuccess: "Offer accepted successfully!",
    InvalidOfferId: "Invalid offer ID",
    NewTipsAvailable: "New Tips Available",
    EnterVerificationCode: "Enter the verification code",
    SentCodeTo: "We sent you a 4-digit code to",
    DidntReceiveOTP: "Didn’t receive the OTP?",
    ResendIn: "Resend in",
    ResendOTPButton: "RESEND OTP",
    NoContentAvailable: "No content available",
    // Delivery Side
    EarningsReports: "Earnings & Reports",
    DocumentShow: "Document Show",
    Wallet: "Wallet",
    Support: "Support",
    TodaysEarnings: "Today's Earnings",
    TodaysRides: "Today's Rides",
    WeeklyEarnings: "Weekly's Earnings",
    WeeklyRides: "Weekly's Rides",
    PickupFrom: "PICKUP FROM",
    DeliverTo: "DELIVER TO",
    RouteMap: "Route Map",
    DeliverySchedule: "Delivery Schedule",
    PickupDate: "Pickup Date",
    PickupTime: "Pickup Time",
    OfferStatus: "Offer Status",
    Reject: "Reject",
    AcceptDelivery: "Accept Delivery",
    RejectDelivery: "Reject Delivery",
    RejectDeliveryConfirm: "Are you sure you want to reject this delivery?",
    TotalEarnings: "Total Earnings",
    Activity: "Activity",
    OnlineHrs: "Online Hrs",
    Trips: "Trips",
    CashTrip: "Cash Trip",
    HowCanWeHelp: "How can we help?",
    TypeHere: "Type Here...",
    Submit: "Submit",
    AvailableBalance: "Your Available Balance",
    Withdraw: "Withdraw",
    AddAmount: "Add Amount",
    AddMoney: "Add Money",
    WithdrawMoney: "Withdraw Money",
    EnterAmount: "Enter amount",
    Confirm: "Confirm",
    Sun: "SUN",
    Mon: "MON",
    Tue: "TUE",
    Wed: "WED",
    Thu: "THU",
    Fri: "FRI",
    Sat: "SAT",
    SuccessLabel: "Success",
    DeliveryAcceptedSuccess: "Delivery accepted successfully!",
    FailedLoadOrders: "Failed to fetch order details",
    SendOffer: "Send Offer",
    StartPickup: "Start Pickup",
    MarkAsPickedUp: "Mark as Picked Up",
    StartDelivery: "Start Delivery",
    MarkAsDelivered: "Mark as Delivered",
    OrderCompleted: "Order Completed",
    OrderCancelled: "Order Cancelled",
    Processing: "Processing...",
    PickupOtpError: "Please enter pickup OTP shared by customer",
    DeliveryOtpError: "Please enter delivery OTP shared by customer",
    ParcelDetails: "Parcel Details",
    PickupLocation: "Pickup Location",
    DropLocation: "Drop Location",
    ParcelInformation: "Parcel Information",
    Price: "Price",
    SenderName: "Sender Name",
    ReceiverName: "Receiver Name",
    ReceiverPhone: "Receiver Phone",
    PackageSize: "Package Size",
    ConsignmentType: "Consignment Type",
    ShipmentType: "Shipment Type",
    MakeOffer: "Make Offer",
    AmountWithCurrency: "Amount ($)",
    EnterAmount: "Enter Amount",
    TypeMessageHere: "Type your message here...",
    CancelOrderConfirm: "Are you sure you want to cancel this order?",
    CreateAccount: "Create an account",
    AlreadyHaveAccount: "Already have an account",
    EnterFullNameError: "Please enter your full name.",
    EnterEmailError: "Please enter your email address.",
    ValidEmailError: "Please enter a valid email address.",
    EnterAddressError: "Please enter your address.",
    UploadProfileImageError: "Please upload your profile image.",
    UploadDocuments: "Upload Documents",
    UploadIdDocument: "Upload ID Document",
    UploadDrivingLicense: "Upload Driving License",
    UploadVehiclePapers: "Upload Vehicle Papers",
    UploadDocumentsError: "Please upload all required documents.",
    DrivingLicenseNumber: "Driving License Number",
    BankName: "Bank Name",
    AccountNumber: "Account Number",
    IFSCCode: "IFSC Code",
    EnterLicenseNumberError: "Please enter your driving license number.",
    EnterPhoneNumberError: "Please enter your phone number.",
    EnterBankNameError: "Please enter your bank name.",
    EnterAccountNumberError: "Please enter your bank account number.",
    EnterIFSCCodeError: "Please enter your bank's IFSC code.",
    VehicleSetup: "Vehicle Setup",
    SelectVehicleType: "Select vehicle type",
    EnterVehicleNumber: "Enter vehicle number",
    UploadVehicleRegistration: "Upload vehicle registration",
    SelectVehicleTypeError: "Please select a vehicle type.",
    EnterVehicleNumberError: "Please enter the vehicle number.",
    UploadVehicleRegistrationError: "Please upload vehicle registration.",
    SaveAndContinue: "Save & Continue",
    Car: "Car",
    Bike: "Bike",
    Van: "Van",
    Truck: "Truck",
    Confirmation: "Confirmation",
    Yes: "Yes",
    No: "No",
    BankSetup: "Bank Setup",
    EnterBankName: "Enter bank name",
    EnterAccountNumber: "Enter account number",
    EnterIFSCCode: "Enter IFSC code",
    SaveAndFinish: "Save & Finish",
    Message: "Message",
    RateYourDelivery: "Rate your delivery",
    ViewOffer: "View Offer",
    TrackDetail: "Track Detail",
    TrackingPackage: "Tracking Package",
    Done: "Done",
    RatingSuccess: "Thanks for your rating!",
    ParcelUpdated: "Parcel updated",
    OrderNumber: "Order Number: ",
    OK: "OK",
    PickupAndDrop: "Pickup & Drop",
    AddPickupLocation: "Add Pickup Location",
    AddDropLocation: "Add Drop Location",
    ShipmentSenderDetails: "Shipment & Sender Details",
    SenderMobileNumber: "Sender Mobile Number",
    ReceiverDetails: "Receiver Details",
    ReceiverMobileNumber: "Receiver Mobile Number",
    ExtraMessage: "Extra Message",
    AddParcelImage: "Add Parcel Image",
    SendRequest: "Send Request",
    Standard: "Standard",
    Express: "Express",
    Normal: "Normal",
    Fast: "Fast",
    PickupLocationRequired: "Pickup location is required",
    DropLocationRequired: "Drop location is required",
    PickupRequestSuccess: "Pickup request submitted successfully!",
    FillRequiredFieldsError: "Please fill all required fields correctly",
    AssigningDriver: "Assigning driver...",
    OTP: "OTP",
    Size: "Size",
    Type: "Type",
    Service: "Service",
    Pickup: "Pickup",
    Drop: "Drop",
    Calculating: "Calculating...",
    AddAddress: "Add Address",
    HomeType: "Home",
    HomeType: "Home",
    OfficeType: "Office",
    Today: "Today",
    Yesterday: "Yesterday",
    OfferAcceptedSuccess: "Offer accepted successfully!",
    OfferAcceptFailed: "Failed to accept offer",
    SomethingWentWrong: "Something went wrong",
    CounterOfferSent: "Counter offer sent successfully!",
    CounterOfferFailed: "Failed to send counter offer",
    LoadingMessages: "Loading messages...",
    NoMessagesYetSayHi: "No messages yet. Say hi!",
    TypeAMessage: "Type a message...",
    InvalidOfferID: "Invalid offer ID",
    DeliveryAgent: "Delivery Agent",
    OrderOpen: "Order Open",
    Error: "Error",
    PhoneNotAvailable: "Phone number not available",
    PhoneCallNotSupported: "Phone call not supported",
  },
  mn: {
    ChangeLanguage: "Хэл солих",
    Logout: "Гарах",
    PhysicalData: "Физик өгөгдөл",
    UsefulTips: "Хэрэгтэй зөвлөмжүүд",
    PaymentHistory: "Төлбөрийн түүх",
    Help: "Тусламж",
    ContactInfo: "Холбоо барих мэдээлэл",
    PushNotifications: "Мэдэгдэл",
    UpdateProfile: "Профайлыг шинэчлэх",
    Version: "Хувилбар",
    Profile: "Профайл",
    Add: "Нэмэх",
    // Onboarding
    ShipYourParcel: "Илгээмжээ илгээх",
    ShipAnywhere: "Хаана ч илгээх",
    TrackYourParcel: "Илгээмжээ хянах",
    OnboardingDesc1: "Илгээмж илгээх үйл явцыг саадгүй, стрессгүй мэдрээрэй.",
    OnboardingDesc2: "Манай найдвартай, аюулгүй хүргэлтийн үйлчилгээгээр илгээмжээ хил дамнуулан илгээгээрэй.",
    OnboardingDesc3: "Илгээмжийнхээ бодит байршлыг хүссэн үедээ мэдэж, мэдээлэлтэй байгаарай.",
    Skip: "Алгасах",
    Continue: "Үргэлжлүүлэх",
    // Choose Role
    ChooseRole: "Хэрэглэгчийн үүргээ сонгоно уу",
    User: "Хэрэглэгч",
    Delivery: "Хүргэлт",
    PleaseSelectRole: "Үргэлжлүүлэхийн өмнө үүргээ сонгоно уу.",
    // Profile
    EditProfile: "Профайлыг засах",
    MyOrders: "Миний захиалга",
    PrivacyPolicy: "Нууцлалын бодлого",
    TermsConditions: "Үйлчилгээний нөхцөл",
    // Login
    PhoneQuestion: "Таны утасны дугаар хэд вэ?",
    PhoneSubtitle: "Бид таныг баталгаажуулах код илгээх болно",
    PhoneNumber: "Утасны дугаар",
    SelectCountry: "Улс сонгох",
    SearchCountry: "Улс хайх",
    Cancel: "Цуцлах",
    PleaseEnterPhone: "Утасны дугаараа оруулна уу.",
    PleaseEnterValidPhone: "Зөв утасны дугаар оруулна уу (6-15 оронтой).",
    ContinueWithNumber: "Дугаараар үргэлжлүүлэх",
    ContinueWithGoogle: "Google-ээр үргэлжлүүлэх",
    FullName: "Овог нэр",
    Email: "Имэйл",
    Address: "Хаяг",
    Update: "Шинэчлэх",
    // Status Labels
    StatusPending: "Хүлээгдэж буй",
    StatusAssigned: "Оноогдсон",
    StatusGoingToPickup: "Авахаар явж байна",
    StatusPickedUp: "Авсан",
    StatusOnTheWay: "Замдаа",
    StatusArriving: "Ойртож байна",
    StatusDelivered: "Хүргэгдсэн",
    StatusCompleted: "Дууссан",
    StatusCancelled: "Цуцлагдсан",
    // Orders Screen
    Orders: "Захиалгууд",
    Pending: "Хүлээгдэж буй",
    Complete: "Дууссан",
    Canceled: "Цуцлагдсан",
    NoOrdersFound: "Захиалга олдсонгүй",
    TrackingID: "Хяналтын ID",
    StepXofY: "{1}-ээс {0}-р алхам дууссан",
    ViewDetails: "Дэлгэрэнгүй үзэх",
    WriteAReview: "Сэтгэгдэл бичих",
    // General
    Search: "Хайх",
    Notifications: "Мэдэгдэл",
    Home: "Нүүр",
    Inbox: "Ирсэн",
    Tracking: "Хяналт",
    From: "Хаанаас",
    To: "Хаашаа",
    DeliveryStatus: "Хүргэлтийн төлөв",
    CreateParcel: "Илгээмж үүсгэх",
    ShippingHistory: "Тээвэрлэлтийн түүх",
    SelectDeliveryAddress: "Хүргэлтийн хаягаа сонгоно уу",
    OfferAccepted: "Санал хүлээн авсан",
    DriverAcceptedOffer: "Жолооч таны саналыг хүлээн авлаа.",
    Order: "Захиалга",
    Carrier: "Тээвэрлэгч",
    OfferPrice: "Санал болгож буй үнэ",
    MessageLabel: "Мессеж",
    PhoneLabel: "Утас",
    Accept: "ЗӨВШӨӨРӨХ",
    CounterOfferLabel: "ЭСРЭГ САНАЛ",
    Chat: "ЧАТ",
    Back: "Буцах",
    OffersForYourAd: "ТАНЫ ЗАРЫН САНАЛУУД",
    NoOffersAvailable: "Одоогоор таны зард санал ирээгүй байна.",
    FindingDriver: "Жолооч хайж байна",
    DriversLabel: "ЖОЛООЧ НАР",
    RadiusLabel: "РАДИУС",
    ScanningArea: "ОРЧНЫГ ШАЛГАЖ БАЙНА",
    CancelSearch: "ХАЙЛТЫГ ЦУЦЛАХ",
    RetryLabel: "ДАХИН ОРОЛДОХ",
    SearchingDrivers: "Боломжтой жолооч хайж байна...",
    ConnectingNetwork: "Сүлжээнд холбогдож байна",
    DriverConfirmed: "Жолооч баталгаажсан • Хүлээн авахаар бэлтгэж байна",
    DriverEnRoute: "Жолооч явж байна • ETA тооцоолж байна",
    ParcelCollected: "Илгээмжийг авсан • Замдаа",
    ParcelDelivered: "Илгээмжийг хүргэж дууссан",
    SearchInboxPlaceholder: "Нэр, хяналтын ID-аар хайх...",
    NoChatsYet: "Одоогоор чат алга",
    NoConversationsSubtitle: "Таны харилцан ярианууд энд харагдах болно",
    SessionExpired: "Холболтын хугацаа дууслаа. Дахин нэвтэрнэ үү.",
    FailedLoadChats: "Чатуудыг ачаалж чадсангүй. Дахин оролдоно уу.",
    NoMessagesYet: "Мессеж алга",
    Unknown: "Үл мэдэгдэх",
    Today: "Өнөөдөр",
    Yesterday: "Өчигдөр",
    DeliveryAgent: "Хүргэлтийн ажилтан",
    TypeAMessage: "Мессеж бичих...",
    LoadingMessages: "Мессежүүдийг ачаалж байна...",
    NoMessagesYetSayHi: "Одоогоор мессеж алга. Сайн уу гэж хэлээрэй!",
    OrderOpen: "Захиалга нээлттэй",
    ErrorLabel: "Алдаа",
    PhoneNotAvailable: "Утасны дугаар байхгүй байна",
    PhoneCallNotSupported: "Утасны дуудлага хийх боломжгүй байна",
    SomethingWentWrong: "Ямар нэг зүйл буруу боллоо",
    FailedAcceptOffer: "Саналыг хүлээн авч чадсангүй",
    FailedSendCounterOffer: "Эсрэг саналыг илгээж чадсангүй",
    CounterOfferSent: "Эсрэг саналыг амжилттай илгээлээ!",
    OfferAcceptedSuccess: "Саналыг амжилттай хүлээн авлаа!",
    InvalidOfferId: "Буруу саналын ID",
    ThisWeek: "Энэ долоо хоног",
    GeneralNotification: "Ерөнхий мэдэгдэл",
    Sound: "Дуу",
    Vibrate: "Чичиргээ",
    NewTipsAvailable: "Шинэ зөвлөгөө боломжтой",
    EnterVerificationCode: "Баталгаажуулах кодыг оруулна уу",
    SentCodeTo: "Бид таны {0} дугаарт 4 оронтой код илгээсэн",
    DidntReceiveOTP: "Код ирээгүй юу?",
    ResendIn: "Дахин илгээх хугацаа",
    ResendOTPButton: "КОД ДАХИН ИЛГЭЭХ",
    NoContentAvailable: "Агуулга байхгүй байна",
    // Delivery Side
    EarningsReports: "Орлого ба тайлан",
    DocumentShow: "Баримт бичиг харах",
    Wallet: "Түрүүвч",
    Support: "Тусламж",
    TodaysEarnings: "Өнөөдрийн орлого",
    TodaysRides: "Өнөөдрийн аялал",
    WeeklyEarnings: "Долоо хоногийн орлого",
    WeeklyRides: "Долоо хоногийн аялал",
    PickupFrom: "АВАХ ГАЗАР",
    DeliverTo: "ХҮРГЭХ ГАЗАР",
    RouteMap: "Маршрутын зураг",
    DeliverySchedule: "Хүргэлтийн хуваарь",
    PickupDate: "Авах огноо",
    PickupTime: "Авах цаг",
    OfferStatus: "Саналын төлөв",
    Reject: "Татгалзах",
    AcceptDelivery: "Хүргэлтийг зөвшөөрөх",
    RejectDelivery: "Хүргэлтээс татгалзах",
    RejectDeliveryConfirm: "Та энэ хүргэлтээс татгалзахдаа итгэлтэй байна уу?",
    TotalEarnings: "Нийт орлого",
    Activity: "Үйл ажиллагаа",
    OnlineHrs: "Онлайн цаг",
    Trips: "Аялал",
    CashTrip: "Бэлэн мөнгөний аялал",
    HowCanWeHelp: "Бид танд яаж туслах вэ?",
    TypeHere: "Энд бичнэ үү...",
    Submit: "Илгээх",
    AvailableBalance: "Таны боломжтой үлдэгдэл",
    Withdraw: "Зарлага гаргах",
    AddAmount: "Мөнгө нэмэх",
    AddMoney: "Мөнгө нэмэх",
    WithdrawMoney: "Мөнгө гаргах",
    EnterAmount: "Дүн оруулна уу",
    Confirm: "Баталгаажуулах",
    Sun: "НЯМ",
    Mon: "ДАВ",
    Tue: "МЯГ",
    Wed: "ЛХА",
    Thu: "ПҮР",
    Fri: "БАА",
    Sat: "БЯМ",
    SuccessLabel: "Амжилттай",
    DeliveryAcceptedSuccess: "Хүргэлтийг амжилттай зөвшөөрлөө!",
    FailedLoadOrders: "Захиалгын мэдээллийг ачаалж чадсангүй",
    SendOffer: "Санал илгээх",
    StartPickup: "Авч эхлэх",
    MarkAsPickedUp: "Авсан гэж тэмдэглэх",
    StartDelivery: "Хүргэлтийг эхлүүлэх",
    MarkAsDelivered: "Хүргэгдсэн гэж тэмдэглэх",
    OrderCompleted: "Захиалга дууссан",
    OrderCancelled: "Захиалга цуцлагдсан",
    Processing: "Боловсруулж байна...",
    PickupOtpError: "Хэрэглэгчийн өгсөн авах OTP-г оруулна уу",
    DeliveryOtpError: "Хэрэглэгчийн өгсөн хүргэлтийн OTP-г оруулна уу",
    ParcelDetails: "Илгээмжийн дэлгэрэнгүй",
    PickupLocation: "Авах байршил",
    DropLocation: "Хүргэх байршил",
    ParcelInformation: "Илгээмжийн мэдээлэл",
    Price: "Үнэ",
    SenderName: "Илгээгчийн нэр",
    ReceiverName: "Хүлээн авагчийн нэр",
    ReceiverPhone: "Хүлээн авагчийн утас",
    PackageSize: "Багцын хэмжээ",
    ConsignmentType: "Ачааны төрөл",
    ShipmentType: "Тээвэрлэлтийн төрөл",
    MakeOffer: "Санал болгох",
    AmountWithCurrency: "Дүн (€)",
    EnterAmount: "Дүн оруулна уу",
    TypeMessageHere: "Мессежээ энд бичнэ үү...",
    CancelOrderConfirm: "Та энэ захиалгыг цуцлахдаа итгэлтэй байна уу?",
    CreateAccount: "Бүртгэл үүсгэх",
    AlreadyHaveAccount: "Бүртгэлтэй хэрэглэгч",
    EnterFullNameError: "Бүтэн нэрээ оруулна уу.",
    EnterEmailError: "Имэйл хаягаа оруулна уу.",
    ValidEmailError: "Зөв имэйл хаяг оруулна уу.",
    EnterAddressError: "Хаягаа оруулна уу.",
    UploadProfileImageError: "Профайл зургаа оруулна уу.",
    UploadDocuments: "Баримт бичиг байршуулах",
    UploadIdDocument: "Иргэний үнэмлэх байршуулах",
    UploadDrivingLicense: "Жолооны үнэмлэх байршуулах",
    UploadVehiclePapers: "Автомашины бичиг баримт байршуулах",
    UploadDocumentsError: "Шаардлагатай бүх баримт бичгийг байршуулна уу.",
    DrivingLicenseNumber: "Driving License Number",
    BankName: "Bank Name",
    AccountNumber: "Account Number",
    IFSCCode: "IFSC Code",
    EnterLicenseNumberError: "Please enter your driving license number.",
    EnterPhoneNumberError: "Please enter your phone number.",
    EnterBankNameError: "Please enter your bank name.",
    EnterAccountNumberError: "Please enter your bank account number.",
    EnterIFSCCodeError: "Please enter your bank's IFSC code.",
    VehicleSetup: "Тээврийн хэрэгслийн тохиргоо",
    SelectVehicleType: "Тээврийн хэрэгслийн төрөл сонгох",
    EnterVehicleNumber: "Улсын дугаар оруулна уу",
    UploadVehicleRegistration: "Тээврийн хэрэгслийн гэрчилгээ байршуулах",
    SelectVehicleTypeError: "Тээврийн хэрэгслийн төрлийг сонгоно уу.",
    EnterVehicleNumberError: "Тээврийн хэрэгслийн дугаарыг оруулна уу.",
    UploadVehicleRegistrationError: "Тээврийн хэрэгслийн гэрчилгээг байршуулна уу.",
    SaveAndContinue: "Хадгалах ба үргэлжлүүлэх",
    Car: "Суудлын тэрэг",
    Bike: "Мотоцикл",
    Van: "Микро автобус",
    Truck: "Ачааны машин",
    Confirmation: "Баталгаажуулалт",
    Yes: "Тийм",
    No: "Үгүй",
    Message: "Мессеж",
    RateYourDelivery: "Хүргэлтийг үнэлэх",
    ViewOffer: "Санал харах",
    TrackDetail: "Дэлгэрэнгүй хянах",
    TrackingPackage: "Илгээмж хянах",
    Done: "Дууссан",
    RatingSuccess: "Үнэлгээ өгсөнд баярлалаа!",
    ParcelUpdated: "Илгээмж шинэчлэгдсэн",
    OrderNumber: "Захиалгын дугаар: ",
    OK: "ОК",
    PickupAndDrop: "Авах ба Хүргэх",
    AddPickupLocation: "Авах байршил нэмэх",
    AddDropLocation: "Хүргэх байршил нэмэх",
    ShipmentSenderDetails: "Тээвэрлэлт ба Илгээгчийн мэдээлэл",
    SenderMobileNumber: "Илгээгчийн утасны дугаар",
    ReceiverDetails: "Хүлээн авагчийн мэдээлэл",
    ReceiverMobileNumber: "Хүлээн авагчийн утасны дугаар",
    ExtraMessage: "Нэмэлт мессеж",
    AddParcelImage: "Илгээмжийн зураг нэмэх",
    SendRequest: "Хүсэлт илгээх",
    Standard: "Стандарт",
    Express: "Экспресс",
    Normal: "Ердийн",
    Fast: "Хурдан",
    PickupLocationRequired: "Авах байршил шаардлагатай",
    DropLocationRequired: "Хүргэх байршил шаардлагатай",
    PickupRequestSuccess: "Авах хүсэлтийг амжилттай илгээлээ!",
    FillRequiredFieldsError: "Шаардлагатай бүх талбарыг зөв бөглөнө үү",
    AssigningDriver: "Жолооч оноож байна...",
    OTP: "OTP",
    Size: "Хэмжээ",
    Type: "Төрөл",
    Service: "Үйлчилгээ",
    Pickup: "Авах",
    Drop: "Хүргэх",
    Calculating: "Тооцоолж байна...",
    AddAddress: "Хаяг нэмэх",
    HomeType: "Гэр",
    HomeType: "Гэр",
    OfficeType: "Оффис",
    Today: "Өнөөдөр",
    Yesterday: "Өчигдөр",
    OfferAcceptedSuccess: "Саналыг амжилттай хүлээн авлаа!",
    OfferAcceptFailed: "Саналыг хүлээн авахад алдаа гарлаа",
    SomethingWentWrong: "Ямар нэг зүйл буруу боллоо",
    CounterOfferSent: "Сөрөг саналыг амжилттай илгээлээ!",
    CounterOfferFailed: "Сөрөг саналыг илгээхэд алдаа гарлаа",
    LoadingMessages: "Мессежийг ачаалж байна...",
    NoMessagesYetSayHi: "Мессеж алга. Сайн уу гэж хэлээрэй!",
    TypeAMessage: "Мессеж бичих...",
    InvalidOfferID: "Буруу саналын ID",
    DeliveryAgent: "Хүргэлтийн агент",
    OrderOpen: "Захиалга нээлттэй",
    Error: "Алдаа",
    PhoneNotAvailable: "Утасны дугаар байхгүй",
    PhoneCallNotSupported: "Утасны дуудлага хийх боломжгүй",
    SelectLanguage: "Хэл сонгох",
  },
});

export default strings;
