import { Dimensions, StyleSheet } from 'react-native';
import font from '../../../theme/font';

const { width } = Dimensions.get('window');
const YELLOW = '#FFCC00';
const DARK = '#1C1C1E';
const GRAY_BG = '#F2F2F7';
const LIGHT_TEXT = '#8E8E93';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F0F0F0',
    padding: 4,
    borderRadius: 30,
    marginBottom: 24,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 26,
    justifyContent: "center"
  },
  activeTabButton: {
    backgroundColor: YELLOW,
    shadowColor: YELLOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: LIGHT_TEXT,
    fontFamily: font.MonolithRegular,
  },
  activeTabText: {
    color: '#000',
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: DARK,
    marginBottom: 16,
    marginLeft: 4,
    fontFamily: font.MonolithRegular,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    marginBottom: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#F2F2F7',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  titleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#FFF9E6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: DARK,
    fontFamily: font.MonolithRegular,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: font.MonolithRegular,
  },
  verifiedBadge: { backgroundColor: '#E1F8E9' },
  reviewBadge: { backgroundColor: '#E3F2FD' },
  pendingBadge: { backgroundColor: '#FFF3E0' },
  verifiedText: { color: '#34C759' },
  reviewText: { color: '#007AFF' },
  pendingText: { color: '#FF9500' },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  infoItem: {
    width: '50%',
    marginBottom: 16,
  },
  infoLabel: {
    fontSize: 12,
    color: LIGHT_TEXT,
    marginBottom: 4,
    fontFamily: font.MonolithRegular,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '600',
    color: DARK,
    fontFamily: font.MonolithRegular,
  },
  docImageWrapper: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: GRAY_BG,
    marginTop: 10,
  },
  image: {
    width: '100%',
    height: 180,
    backgroundColor: GRAY_BG,
  },
  imageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: 8,
    alignItems: 'center',
  },
  overlayText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: font.MonolithRegular,
  },
  bankCard: {
    backgroundColor: DARK,
    borderRadius: 24,
    padding: 24,
    minHeight: 220,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  bankHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bankName: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: font.MonolithRegular,
  },
  bankChip: {
    width: 48,
    height: 36,
    backgroundColor: YELLOW,
    borderRadius: 8,
    opacity: 0.9,
  },
  accountNumber: {
    color: '#FFF',
    fontSize: 22,
    letterSpacing: 3,
    marginVertical: 24,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    textAlign: 'center',
  },
  bankFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  bankLabel: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 10,
    textTransform: 'uppercase',
    marginBottom: 4,
    fontFamily: font.MonolithRegular,
  },
  bankValue: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: font.MonolithRegular,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    marginTop: 50,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: DARK,
    marginTop: 20,
    fontFamily: font.MonolithRegular,
  },
  emptySubtitle: {
    fontSize: 14,
    color: LIGHT_TEXT,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
    fontFamily: font.MonolithRegular,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
  },
  loadingText: {
    marginTop: 12,
    color: LIGHT_TEXT,
    fontWeight: '500',
    fontFamily: font.MonolithRegular,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    flex: 1,
    width: Dimensions.get('window').width,
  },
});
